### ISSUE TITLE
Docker build broke

### ISSUE THREAD

**Issue by Corwin7** [wadmiraal/docker-drupal#11]
#  docker build -t corwin/drupal . 
...
Step 46 : RUN /etc/init.d/mysql start &&    cd /var/www &&  drupal module:download admin_toolbar 8.x-1.10 &&    drupal module:install admin_toolbar &&  drupal module:install simpletest
 ---> Running in 1538aa394250
Starting MySQL database server: mysqld ..
Checking for tables which need an upgrade, are corrupt or were 
not closed cleanly..

 [WARNING] In order to list all of the available commands you should install drupal first.                              

  [Drupal\Core\DependencyInjection\ContainerNotInitializedException]  
  \Drupal::$container is not initialized yet. \Drupal::setContainer() must be called with a real container.  

module:download [--latest] [--] [<module>]...

The command '/bin/sh -c /etc/init.d/mysql start &&  cd /var/www &&  drupal module:download admin_toolbar 8.x-1.10 &&    drupal module:install admin_toolbar &&  drupal module:install simpletest' returned a non-zero code: 1

**Comment by wadmiraal** [comment]
The issue with the Drupal 8 images is that [Drupal Console](https://github.com/hechoendrupal/DrupalConsole) is still undergoing many changes. This broken build is one typical example of an API change (not the first time this happens). Anyway, updated to Drupal 8.0.2, fixed the `module:install` call. It builds fine now :-).
