### ISSUE TITLE
Using it on Windows

### ISSUE THREAD

**Issue by lsolesen** [wadmiraal/docker-drupal#14]
I can successfully run a docker and pull your docker. However, when navigating to http://localhost:80 on my WIndows 10, I just get a blank page:

```
docker run -d -p 8080:80 -t wadmiraal/drupal:7
```

I am using Docker Toolbox. Do you have any insights as to how get it working?

**Comment by lsolesen** [comment]
Ah, seems that my friend could be:

```
docker-machine ip
```

**Comment by wrender** [comment]
That's correct. On Windows and Mac there is a virtual machine that  
sits in between the OS, and the container. For this reason you need to  
use this command to get the IP of the docker.

Quoting Lars Olesen notifications@github.com:

**Comment by visitdigital** [comment]
Seen this?!

https://blog.docker.com/2016/03/docker-for-mac-windows-beta/

On 3 Apr 2016, at 17:09, OtherData notifications@github.com wrote:

That's correct. On Windows and Mac there is a virtual machine that 
sits in between the OS, and the container. For this reason you need to  
use this command to get the IP of the docker.

Quoting Lars Olesen notifications@github.com:

**Comment by wadmiraal** [comment]
@visitdigital That looks great!

@lsolesen I don't know if you read my tutorial [here](http://wadmiraal.net/lore/2015/03/27/use-docker-to-kickstart-your-drupal-development/) (_"Preamble: attention non-Linux users"_)? I link to a few articles for Windows users. Being a Linux user myself, I don't know what it exactly takes to run this on Windows or Mac OS. Docker is a very Linux-centric product (that's the whole point; it uses features that Mac OS and Windows don't have, bypassing the need for virtualization).

Anyway, did using `docker-machine ip` solve your issue? Can I close this ticket?

**Comment by lsolesen** [comment]
Yeah. It solved the issue. Thanks.
Den 05/04/2016 11.47 skrev "Wouter Admiraal" notifications@github.com:
