### ISSUE TITLE
Drupal Console run error

### ISSUE THREAD

**Issue by cristianobento** [wadmiraal/docker-drupal#16]
Hi guys!

Running this command: drupal --target=docker.wadmiraal_drupal module:download ctools 8.x-3.0-alpha19

I receive the following errors: 
PHP Warning:  file_get_contents(): Filename cannot be empty in phar:///usr/local/bin/drupal/src/Helper/RemoteHelper.php on line 57
PHP Warning:  file_get_contents(): Filename cannot be empty in phar:///usr/local/bin/drupal/src/Helper/RemoteHelper.php on line 62
Error with private key

I'm using the 1.0.0-beta3 version of Drupal Console

Could you help me with this issue?

**Comment by wadmiraal** [comment]
This is related to the [following issue](https://github.com/hechoendrupal/DrupalConsole/issues/2037). Unfortunately, there's not much I can do here :-). It's tied to Drupal Console, not the Docker image.
