### ISSUE TITLE
why do you remove sh?

### ISSUE THREAD

**Issue by yurii-github** [wadmiraal/docker-drupal#19]
why do you do this

> RUN rm /bin/sh && ln -s /bin/bash /bin/sh

what's the point?

regards

**Comment by wadmiraal** [comment]
Frankly, I can't remember ':-D. I was having trouble with something, and Googl'ing around suggested this fix. I know it has worked ever since, but I don't remember what it was. I will try removing it, see if it works any better.

**Comment by wadmiraal** [comment]
Works fine...
