### ISSUE TITLE
Docker not building

### ISSUE THREAD

**Issue by justinlevi** [wadmiraal/docker-drupal#20]
I'm seeing a few issues building the docker image as of yesterday. Seems that there are some packages that have changed recently as well as a composer issue? Just wondering if this is a known problem?

**Comment by justinlevi** [comment]
Here's a bit more information: 

```
Step 48 : RUN cd /var &&    drupal site:new www 8.2.2
 ---> Running in 1063a774e83d
PHP Warning:  Invalid argument supplied for foreach() in /root/.composer/vendor/drupal/console/src/Utils/RequirementChecker.php on line 71
PHP Stack trace:
PHP   1. {main}() /root/.composer/vendor/drupal/console/bin/drupal:0
PHP   2. require() /root/.composer/vendor/drupal/console/bin/drupal:4
PHP   3. Symfony\Component\Console\Application->run() /root/.composer/vendor/drupal/console/bin/drupal.php:115
PHP   4. Drupal\Console\Application->doRun() /root/.composer/vendor/symfony/console/Application.php:124
PHP   5. Drupal\Console\Utils\RequirementChecker->validate() /root/.composer/vendor/drupal/console/src/Application.php:273
PHP   6. Drupal\Console\Utils\RequirementChecker->checkRecommendedExtensions() /root/.composer/vendor/drupal/console/src/Utils/RequirementChecker.php:117

Warning: Invalid argument supplied for foreach() in /root/.composer/vendor/drupal/console/src/Utils/RequirementChecker.php on line 71

Call Stack:
    0.0001     216936   1. {main}() /root/.composer/vendor/drupal/console/bin/drupal:0
    0.0007     251672   2. require('/root/.composer/vendor/drupal/console/bin/drupal.php') /root/.composer/vendor/drupal/console/bin/drupal:4
    0.6632    7983584   3. Symfony\Component\Console\Application->run() /root/.composer/vendor/drupal/console/bin/drupal.php:115
    0.6668    8346504   4. Drupal\Console\Application->doRun() /root/.composer/vendor/symfony/console/Application.php:124
    0.7926   19489152   5. Drupal\Console\Utils\RequirementChecker->validate() /root/.composer/vendor/drupal/console/src/Application.php:273
    0.7955   19498864   6. Drupal\Console\Utils\RequirementChecker->checkRecommendedExtensions() /root/.composer/vendor/drupal/console/src/Utils/RequirementChecker.php:117


 Pass a «true» value to «shellexec_output» key in your config.yml file to see interactively Composer's output or        
 «false» to hide it              
```

**Comment by justinlevi** [comment]
Found this issue which provides an updated `phpcheck.yml` but I'm not sure if or how we'd want to include that here. 

https://github.com/hechoendrupal/DrupalConsole/issues/2582

**Comment by justinlevi** [comment]
The image seems to build with the error above but when I try to get a container up and running apache doesn't start. 

`⚡ docker run -d -p 8080:80 -p 8022:22 -t justinlevi/drupal`

```
⚡ sudo docker exec -i -t e67eb4317da1 /bin/bash
Password:
root@e67eb4317da1:/# service --status-all
 [ - ]  apache2
 [ - ]  blackfire-agent
 [ - ]  bootlogs
 [ - ]  bootmisc.sh
 [ - ]  checkfs.sh
 [ - ]  checkroot-bootclean.sh
 [ - ]  checkroot.sh
 [ - ]  cron
 [ - ]  exim4
 [ - ]  hostname.sh
```

```
root@e67eb4317da1:/# service apache2 restart
[FAIL] Restarting web server: apache2 failed!
[warn] The apache2 configtest failed. ... (warning).
Output of config test was:
AH00526: Syntax error on line 222 of /etc/apache2/apache2.conf:
Invalid command '-e', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.
root@e67eb4317da1:/# 
```

Here's what I"m seeing in the `/etc/apache2/apache2.conf` file in vim: 

![screen shot 2016-11-16 at 8 55 36 am](https://cloud.githubusercontent.com/assets/1117989/20349941/a5fe812a-abda-11e6-95ad-9f7e367bb6dd.jpg)

**Comment by wadmiraal** [comment]
Hi. Did you pull the latest version? I had some issues with builds lately. I changed the way Drupal Console is installed, pinning it to a specific version. After that, the builds worked again.

**Comment by justinlevi** [comment]
Yeah, I'm on the latest commit `8f1f1f9e451209fdc6f36ea52004071b5d452249`

**Comment by wadmiraal** [comment]
Yes, I see. I can reproduce the error.

**Comment by wadmiraal** [comment]
Bloody Console. It's really not stable, is it? I run into many issues with that thing... Let me see if downgrading to another release works...

**Comment by justinlevi** [comment]
Yeah, exactly. I've run into more problems than solutions with console at this point. Looking forward to a 1.x release. 

Does it make sense to switch back to drush until 1.0 and a confirmed stable release? 

We could leave the console install portion commented out in the Dockerfile in case someone wants to fiddle with that... Just a thought.

**Comment by wadmiraal** [comment]
Yeah, I'm considering it more and more myself... I'll have a look.

**Comment by wadmiraal** [comment]
So, now it uses Drush for installation and config. I also added a build script, which tests all services and checks if Drupal is running and available. It's now connected to [Travis CI](https://travis-ci.org/wadmiraal/docker-drupal), FTW!
