### ISSUE TITLE
Can not log into container.

### ISSUE THREAD

**Issue by ghost** [wadmiraal/docker-drupal#24]
Hello! Before that, everything was working, now reinstalled the image and can not perform the input to the container across ssh, the same situation phpmyadmin " #1698 - Access denied for user 'root'@'localhost'"

**Comment by vifito** [comment]
I could not access to container via ssh. 

My workaround: 
- Access to container: `docker exec -it <container_name> bash`
- Change root password: `passwd`
- Adding next line to /etc/ssh/sshd_config file: `PermitRootLogin yes`
- Restart ssh service: `/etc/init.d/ssh restart`

**Comment by wadmiraal** [comment]
Thank you vifito. It must be the update to Debian 9. I'll change it. Or, if you want to submit a PR, I'll accept it as well.

**Comment by mishac** [comment]
I added a pr at #25

**Comment by wadmiraal** [comment]
Thanks mishac! Merged.
