### ISSUE TITLE
I can't login to ssh

### ISSUE THREAD

**Issue by mrenzo20** [wadmiraal/docker-drupal#26]
Hi, i can't login to ssh with root:root.
From my local macosx:
ssh root@localhost -p 32773 <- docker port
root@localhost's password: 
Permission denied, please try again.
root@localhost's password: 
Permission denied, please try again.
root@localhost's password: 
root@localhost: Permission denied (publickey,password).

**Comment by wadmiraal** [comment]
I merged #27. This should automatically build the image again in a few minutes.

Could you pull, and start again, see if that fixed it?

**Comment by edurenye** [comment]
I tried and it works

**Comment by wadmiraal** [comment]
Perfect, thanks for the confirmation.

**Comment by edurenye** [comment]
This still gives us a problem when you use 'volume' option as those files will have the uid from the original owner, we can suppose this will be 1000 so our 'drupal' user will be able to edit it, but if we do overwrite /var/www with it the apache won't be able to access it.
This is a normal use case for this when you wan to use it to test your drupal site and you use:
```-v `pwd`/../your-site:/var/www```
