### ISSUE TITLE
can't pull drupal 8.5 image?

### ISSUE THREAD

**Issue by laurencefass** [wadmiraal/docker-drupal#29]
i can't find a working label to pull drupal 8.5. 

docs suggest :8 label should do it, but thats pulling 8.4

any help appreciated

thanks

**Comment by wadmiraal** [comment]
Yes, sorry, I haven't pushed any updates for 8.5 yet... I'll have to tag
and push them :-)

Le lun. 30 avr. 2018 12:08, laurence fass <notifications@github.com> a
écrit :

**Comment by laurencefass** [comment]
please can you update this thread when you do as I would like to continue testing with image. 

thanks

**Comment by wadmiraal** [comment]
Done. They should be built shortly.

https://github.com/wadmiraal/docker-drupal/releases
https://hub.docker.com/r/wadmiraal/drupal/builds/
