### ISSUE TITLE
exceptionally slow on first page load

### ISSUE THREAD

**Issue by laurencefass** [wadmiraal/docker-drupal#30]
the site works ok once cached but first page loads (all of them) are very slow. first page load after login taking up to a minute. 

im testing for first time and i havent mounted any volumes to host.

any suggestions to speed up initial page loads greatly appreciated.

**Comment by wadmiraal** [comment]
Are you on macOS? And if so, are you mounting the database files
(/var/lib/mysql/)?

Le lun. 30 avr. 2018 12:35, laurence fass <notifications@github.com> a
écrit :

**Comment by laurencefass** [comment]
im running windows 10 host docker toolbox (boot2docker guest vm). i've tried other means of installing drupal which seem to run much faster so im not sure its a problem with the setup. once the cache is warmed it works ok on repeat page visits. its the initial load....

**Comment by wadmiraal** [comment]
I cannot test on Windows, unfortunately. I know disk IO can be terrible on
non-Linux machines (I have this issue on my Mac).

I guess you aren't mounting the database files? If you are, could you try
running the mount as -v my/path:/var/lib/mysql:cached?

Le lun. 30 avr. 2018 17:22, laurence fass <notifications@github.com> a
écrit :
