### ISSUE TITLE
PHP 5.4 not PHP 5.6

### ISSUE THREAD

**Issue by visitdigital** [wadmiraal/docker-drupal#4]
First of all...thanks for this it is a great start for me to use as my Drupal Dev environment. You mention in the Readme that it is using PHP 5.6 but in fact it is using 5.4. Can we get a release to correct that?

**Comment by wadmiraal** [comment]
Hi there. Good to know it's useful to you :-). The latest version uses Debian Jessie. So that _should_ install PHP 5.6. How did you install the image? Via Github (using `docker build`) or via Docker Hub (`docker pull wadmiraal/drupal`)?

**Comment by visitdigital** [comment]
Ah you're right I saw you updated a few days ago but I have been using a old version of the docker file on my local machine.

How have you found the performance of the container with medium sites sites installed? It's been quite slow for me and I can't workout why. DB connection is very fast, but page build time is 4-5 times slower than my old VM (I'm quite new to Docker)

On 18 Dec 2015, at 20:40, Wouter Admiraal notifications@github.com wrote:

Hi there. Good to know it's useful to you :-). The latest version uses Debian Jessie. So that should install PHP 5.6. How did you install the image? Via Github (using docker build) or via Docker Hub (docker pull wadmiraal/drupal)?

**Comment by wrender** [comment]
Hi Wouter,

I used 'docker pull wadmirall/drupal' from your blog example.

I'm just learning Drupal module development so I'm going to take a  
look at XDebug as it is recommended by the Drupal Book I am reading.  
I'm new to Vagrant and Docker but I have been doing web development  
for about 15 years.  I am amazed at how powerful these tools are.

I've also installed this Vagrant image as it includes XDebug, Node.js  
and Ruby which I will use :  http://www.drupalvm.com/.

Do you think it would be possible to include these features in your docker?

Thanks,

Wes

Quoting Wouter Admiraal notifications@github.com:

**Comment by wadmiraal** [comment]
@VisitDigital I know that, on MacOS or Windows, the file system is very
slow (because it uses a VM to run Docker). I am on Linux, so it's almost as
fast as if it were running on my machine directly. What OS are you on?

**Comment by wadmiraal** [comment]
@Wes Hi Wes. XDebug could definitely be added, it can be useful indeed.
Although I prefer Blackfire, which _is_ included. As for Ruby and Node.js,
why would you want these?

**Comment by wrender** [comment]
@wadmiraal   My apologies. At the time of writing I was just learning docker.  I now see that it would be unnecessary to have nodejs and ruby in the container as it is intended to have all file/development done on the local filesystem.   I'm not familiar with Blackfire, but i'm reading a drupal book that is recommending xdebug.  Maybe I can try and patch your code to include an option for xdebug?

**Comment by wadmiraal** [comment]
I will add it. It will become available from the latest `7.x` and `master` branches on Github, and `7` and `8` tags in the Docker registry.

It will be available for versions starting at `7.42` and `8.0.2` as soon as they are released on Drupal.org.

**Comment by wadmiraal** [comment]
Pushed. If you use the Git repo and build manually, you can start doing so now. If you use the Docker registry, wait for the builds to finish ([check progress here](https://hub.docker.com/r/wadmiraal/drupal/builds/)) and use `docker pull wadmiraal/drupal(:version)`.

**Comment by wrender** [comment]
Great @wadmiraal .  Will check out building it manually today!
